// File: build.mjs
import fs from 'fs-extra';
import path from 'path';

// Define paths
const assetsDir = path.join(process.cwd(), 'src', 'assets');
const generatedFile = path.join(process.cwd(), 'src', 'generated-assets.mjs');
const outputDir = path.join(process.cwd(), 'dist');
const imagesDir = path.join(assetsDir, 'images');
const outputImagesDir = path.join(outputDir, 'assets', 'images');

async function copyImages() {
  try {
    console.log(`Copying images from ${imagesDir} to ${outputImagesDir}...`);
    await fs.ensureDir(outputImagesDir);
    await fs.copy(imagesDir, outputImagesDir);
    console.log('Successfully copied images.');
  } catch (error) {
    console.error(`\n[ERROR] Could not copy images:`);
    console.error(error.message);
    process.exit(1);
  }
}

async function buildAssets() {
  console.log('Generating static assets module...');

  const assetPaths = {
    clientJs: path.join(assetsDir, 'client.mjs'),
    lazyJs: path.join(assetsDir, 'lazy.mjs'),
    styleCss: path.join(assetsDir, 'style.css'),
    blogCss: path.join(assetsDir, 'blog.css'),
    themeJs: path.join(assetsDir, 'theme.mjs'),
    i18nIndex: path.join(assetsDir, 'i18n', 'index.mjs'),
    faJsonStr: path.join(assetsDir, 'i18n', 'fa.json'),
    enJsonStr: path.join(assetsDir, 'i18n', 'en.json'),
  };

  let content = `// This file is auto-generated by build.mjs on ${new Date().toISOString()}.\n`;
  content += '// Do not edit this file directly.\n\n';

  for (const [key, filePath] of Object.entries(assetPaths)) {
    try {
      const fileContent = await fs.readFile(filePath, 'utf-8');
      content += `export const ${key} = ${JSON.stringify(fileContent)};\n`;
    } catch (error) {
      console.error(`\n[ERROR] Could not read file: ${filePath}`);
      console.error(error.message);
      process.exit(1);
    }
  }

  await fs.writeFile(generatedFile, content);
  console.log(`Successfully created ${generatedFile}`);
}

async function main() {
  await buildAssets();
  await copyImages();
}

main();