// File: build.mjs
import fs from 'fs-extra';
import path from 'path';

// مسیرهای ورودی و خروجی را تعریف می‌کنیم
const assetsDir = path.join(process.cwd(), 'src', 'assets');
const generatedFile = path.join(process.cwd(), 'src', 'generated-assets.mjs');
const articlesDir = path.join(process.cwd(), 'src', 'articles');
const generatedArticlesFile = path.join(process.cwd(), 'src', 'articles.generated.mjs');

async function buildAssets() {
  console.log('Generating static assets module...');

  // لیستی از فایل‌هایی که می‌خواهیم محتوایشان را بخوانیم
  const assetPaths = {
    clientJs: path.join(assetsDir, 'client.mjs'),
    lazyJs: path.join(assetsDir, 'lazy.mjs'),
    styleCss: path.join(assetsDir, 'style.css'),
    themeJs: path.join(assetsDir, 'theme.mjs'),
    i18nIndex: path.join(assetsDir, 'i18n', 'index.mjs'),
    faJsonStr: path.join(assetsDir, 'i18n', 'fa.json'),
    enJsonStr: path.join(assetsDir, 'i18n', 'en.json'),
  };

  // شروع ساخت محتوای فایل خروجی
  let content = `// This file is auto-generated by build.mjs on ${new Date().toISOString()}.\n`;
  content += '// Do not edit this file directly.\n\n';

  // به ازای هر فایل، محتوای آن را می‌خوانیم و به صورت یک متغیر export می‌کنیم
  for (const [key, filePath] of Object.entries(assetPaths)) {
    try {
      const fileContent = await fs.readFile(filePath, 'utf-8');
      // از JSON.stringify استفاده می‌کنیم تا محتوا به یک رشته جاوااسکریپت معتبر تبدیل شود
      content += `export const ${key} = ${JSON.stringify(fileContent)};\n`;
    } catch (error) {
      console.error(`\n[ERROR] Could not read file: ${filePath}`);
      console.error(error.message);
      // در صورت خطا، از برنامه خارج می‌شویم
      process.exit(1);
    }
  }
  
  // محتوای نهایی را در فایل خروجی می‌نویسیم
  await fs.writeFile(generatedFile, content);
  console.log(`Successfully created ${generatedFile}`);
}

async function buildArticles() {
  console.log('Generating articles manifest...');

  let files = [];
  try {
    files = await fs.readdir(articlesDir);
  } catch (error) {
    if (error.code === 'ENOENT') {
      await fs.writeFile(
        generatedArticlesFile,
        "// Auto-generated placeholder when no articles are present.\nexport const articles = [];\n",
      );
      console.warn('No articles directory found. Created empty manifest.');
      return;
    }
    throw error;
  }

  const articles = [];
  for (const fileName of files.filter((file) => file.endsWith('.md'))) {
    const filePath = path.join(articlesDir, fileName);
    const raw = await fs.readFile(filePath, 'utf-8');
    const delimiterPattern = /\r?\n---\r?\n/;
    const match = delimiterPattern.exec(raw);
    if (!match) {
      throw new Error('Article file ' + fileName + ' is missing the "---" delimiter surrounded by newlines.');
    }

    const dividerIndex = match.index;
    const frontMatterRaw = raw.slice(0, dividerIndex).trim();
    const body = raw.slice(dividerIndex + match[0].length).trim();
    let meta;
    try {
      meta = JSON.parse(frontMatterRaw);
    } catch (error) {
      throw new Error(`Invalid JSON front matter in ${fileName}: ${error.message}`);
    }

    if (!meta.slug) {
      throw new Error(`Article file ${fileName} must define a "slug" property.`);
    }

    articles.push({ ...meta, content: body, source: fileName });
  }

  articles.sort((a, b) => {
    const dateA = a.publishedAt || '';
    const dateB = b.publishedAt || '';
    if (dateA === dateB) {
      return a.slug.localeCompare(b.slug);
    }
    return dateA < dateB ? 1 : -1;
  });

  const moduleContent = [
    `// Auto-generated article manifest on ${new Date().toISOString()}.`,
    '// Do not edit this file directly.',
    '',
    `export const articles = ${JSON.stringify(articles, null, 2)};`,
    '',
  ].join('\n');

  await fs.writeFile(generatedArticlesFile, moduleContent);
  console.log(`Successfully created ${generatedArticlesFile}`);
}

// تابع اصلی را اجرا می‌کنیم
Promise.all([buildAssets(), buildArticles()])
  .then(() => {
    console.log('All build steps completed successfully.');
  })
  .catch((error) => {
    console.error('Build failed:', error);
    process.exit(1);
  });