// File: build.mjs
import fs from 'fs-extra';
import path from 'path';

// مسیرهای ورودی و خروجی را تعریف می‌کنیم
const assetsDir = path.join(process.cwd(), 'src', 'assets');
const generatedFile = path.join(process.cwd(), 'src', 'generated-assets.mjs');

async function buildAssets() {
  console.log('Generating static assets module...');

  // لیستی از فایل‌هایی که می‌خواهیم محتوایشان را بخوانیم
  const assetPaths = {
    clientJs: path.join(assetsDir, 'client.mjs'),
    styleCss: path.join(assetsDir, 'style.css'),
    themeJs: path.join(assetsDir, 'theme.mjs'),
    i18nIndex: path.join(assetsDir, 'i18n', 'index.mjs'),
    faJsonStr: path.join(assetsDir, 'i18n', 'fa.json'),
    enJsonStr: path.join(assetsDir, 'i18n', 'en.json'),
  };

  // شروع ساخت محتوای فایل خروجی
  let content = `// This file is auto-generated by build.mjs on ${new Date().toISOString()}.\n`;
  content += '// Do not edit this file directly.\n\n';

  // به ازای هر فایل، محتوای آن را می‌خوانیم و به صورت یک متغیر export می‌کنیم
  for (const [key, filePath] of Object.entries(assetPaths)) {
    try {
      const fileContent = await fs.readFile(filePath, 'utf-8');
      // از JSON.stringify استفاده می‌کنیم تا محتوا به یک رشته جاوااسکریپت معتبر تبدیل شود
      content += `export const ${key} = ${JSON.stringify(fileContent)};\n`;
    } catch (error) {
      console.error(`\n[ERROR] Could not read file: ${filePath}`);
      console.error(error.message);
      // در صورت خطا، از برنامه خارج می‌شویم
      process.exit(1);
    }
  }
  
  // محتوای نهایی را در فایل خروجی می‌نویسیم
  await fs.writeFile(generatedFile, content);
  console.log(`Successfully created ${generatedFile}`);
}

// تابع اصلی را اجرا می‌کنیم
buildAssets();