// Data model for the ProGuard marketing experience
import { articles } from './articles.generated.mjs';

export const pageModel = {
  navigation: [
    { id: 'hero', anchor: '#hero', path: '/', labelKey: 'global.nav.home', pages: ['home'] },
    { id: 'why-us', anchor: '#why-us', path: '/why-us', labelKey: 'global.nav.why', pages: ['home', 'why-us'] },
    { id: 'services', anchor: '#services', path: '/services', labelKey: 'global.nav.services', pages: ['home', 'services'] },
    {
      id: 'products',
      anchor: '#products',
      path: '/solutions',
      labelKey: 'global.nav.solutions',
      pages: ['home', 'solutions', 'product-detail'],
    },
    {
      id: 'case-studies',
      anchor: '#case-studies',
      path: '/projects',
      labelKey: 'global.nav.projects',
      pages: ['home', 'projects'],
    },
    {
      id: 'articles',
      anchor: '#articles',
      path: '/articles',
      labelKey: 'global.nav.articles',
      pages: ['home', 'articles', 'article-detail'],
    },
    { id: 'about', anchor: '#credentials', path: '/about', labelKey: 'global.nav.about', pages: ['home', 'about'] },
    { id: 'faq', anchor: '#faq', path: '/faq', labelKey: 'global.nav.faq', pages: ['home', 'faq'] },
    { id: 'contact', anchor: '#contact', path: '/contact', labelKey: 'global.nav.contact', pages: ['home', 'contact'] },
  ],
  hero: {
    titleKey: 'hero.title',
    subtitleKey: 'hero.subtitle',
    ctaPrimaryKey: 'hero.cta',
    ctaSecondaryKey: 'hero.secondaryCta',
    badgesKeys: ['hero.badges.0', 'hero.badges.1', 'hero.badges.2'],
    imageKey: 'hero.main',
  },
  catalogDownloads: {
    eyebrowKey: 'catalog.eyebrow',
    titleKey: 'catalog.title',
    descriptionKey: 'catalog.description',
    downloadLabelKey: 'catalog.download',
    items: [
      {
        id: 'fa',
        href: 'https://pdfhost.io/v/J6FxHuAEBq_ProGuardv1',
        localeLabelKey: 'catalog.items.fa.locale',
        titleKey: 'catalog.items.fa.title',
        descriptionKey: 'catalog.items.fa.description',
        badgeKey: 'catalog.items.fa.badge',
      },
      {
        id: 'en',
        href: 'https://pdfhost.io/v/J6FxHuAEBq_ProGuardv1?lang=en',
        localeLabelKey: 'catalog.items.en.locale',
        titleKey: 'catalog.items.en.title',
        descriptionKey: 'catalog.items.en.description',
        badgeKey: 'catalog.items.en.badge',
      },
    ],
    noteKey: 'catalog.note',
  },
  metrics: [
    { icon: 'shield-up', valueKey: 'metrics.systems.value', labelKey: 'metrics.systems.label' },
    { icon: 'projector', valueKey: 'metrics.projects.value', labelKey: 'metrics.projects.label' },
    { icon: 'globe-grid', valueKey: 'metrics.coverage.value', labelKey: 'metrics.coverage.label' },
    { icon: 'handshake', valueKey: 'metrics.clients.value', labelKey: 'metrics.clients.label' },
  ],
  highlights: {
    eyebrowKey: 'highlights.eyebrow',
    titleKey: 'highlights.title',
    descriptionKey: 'highlights.description',
    items: [
      { icon: 'nano', titleKey: 'highlights.items.nano.title', descriptionKey: 'highlights.items.nano.description' },
      { icon: 'engineering', titleKey: 'highlights.items.engineering.title', descriptionKey: 'highlights.items.engineering.description' },
      { icon: 'handshake', titleKey: 'highlights.items.support.title', descriptionKey: 'highlights.items.support.description' },
      { icon: 'certificate', titleKey: 'highlights.items.certification.title', descriptionKey: 'highlights.items.certification.description' },
    ],
  },
  whyUs: {
    eyebrowKey: 'why.eyebrow',
    titleKey: 'why.title',
    descriptionKey: 'why.description',
    pillars: [
      {
        icon: 'lab-beaker',
        titleKey: 'why.pillars.research.title',
        descriptionKey: 'why.pillars.research.description',
      },
      {
        icon: 'layers',
        titleKey: 'why.pillars.systems.title',
        descriptionKey: 'why.pillars.systems.description',
      },
      {
        icon: 'shield-check',
        titleKey: 'why.pillars.certified.title',
        descriptionKey: 'why.pillars.certified.description',
      },
      {
        icon: 'support',
        titleKey: 'why.pillars.support.title',
        descriptionKey: 'why.pillars.support.description',
      },
    ],
  },
  services: {
    eyebrowKey: 'services.eyebrow',
    titleKey: 'services.title',
    descriptionKey: 'services.description',
    categories: [
      {
        icon: 'spray',
        titleKey: 'services.categories.waterproofing.title',
        itemsKey: 'services.categories.waterproofing.items',
      },
      {
        icon: 'structure',
        titleKey: 'services.categories.coatings.title',
        itemsKey: 'services.categories.coatings.items',
      },
      {
        icon: 'engineering',
        titleKey: 'services.categories.engineering.title',
        itemsKey: 'services.categories.engineering.items',
      },
    ],
    ctaKey: 'services.cta',
  },
  process: {
    eyebrowKey: 'process.eyebrow',
    titleKey: 'process.title',
    steps: [
      { icon: 'calendar', titleKey: 'process.steps.discovery.title', descriptionKey: 'process.steps.discovery.description' },
      { icon: 'engineering', titleKey: 'process.steps.design.title', descriptionKey: 'process.steps.design.description' },
      { icon: 'handshake', titleKey: 'process.steps.execution.title', descriptionKey: 'process.steps.execution.description' },
      { icon: 'award', titleKey: 'process.steps.assurance.title', descriptionKey: 'process.steps.assurance.description' },
    ],
    noteKey: 'process.note',
  },
  caseStudies: {
    eyebrowKey: 'caseStudies.eyebrow',
    titleKey: 'caseStudies.title',
    descriptionKey: 'caseStudies.description',
    cards: [
      {
        icon: 'infrastructure',
        titleKey: 'caseStudies.cards.metro.title',
        subtitleKey: 'caseStudies.cards.metro.subtitle',
        metricKey: 'caseStudies.cards.metro.metric',
        descriptionKey: 'caseStudies.cards.metro.description',
      },
      {
        icon: 'energy',
        titleKey: 'caseStudies.cards.energy.title',
        subtitleKey: 'caseStudies.cards.energy.subtitle',
        metricKey: 'caseStudies.cards.energy.metric',
        descriptionKey: 'caseStudies.cards.energy.description',
      },
      {
        icon: 'arena',
        titleKey: 'caseStudies.cards.arena.title',
        subtitleKey: 'caseStudies.cards.arena.subtitle',
        metricKey: 'caseStudies.cards.arena.metric',
        descriptionKey: 'caseStudies.cards.arena.description',
      },
    ],
  },
  articlesSection: {
    eyebrowKey: 'articles.section.eyebrow',
    titleKey: 'articles.section.title',
    descriptionKey: 'articles.section.description',
    ctaKey: 'articles.section.cta',
  },
  credentials: {
    eyebrowKey: 'credentials.eyebrow',
    titleKey: 'credentials.title',
    timeline: [
      {
        icon: 'calendar',
        timeKey: 'credentials.timeline.start.year',
        titleKey: 'credentials.timeline.start.title',
        descriptionKey: 'credentials.timeline.start.description',
      },
      {
        icon: 'award',
        timeKey: 'credentials.timeline.expansion.year',
        titleKey: 'credentials.timeline.expansion.title',
        descriptionKey: 'credentials.timeline.expansion.description',
      },
      {
        icon: 'partnership',
        timeKey: 'credentials.timeline.global.year',
        titleKey: 'credentials.timeline.global.title',
        descriptionKey: 'credentials.timeline.global.description',
      },
    ],
  },
  testimonials: {
    eyebrowKey: 'testimonials.eyebrow',
    titleKey: 'testimonials.title',
    cards: [
      {
        quoteKey: 'testimonials.cards.metro.quote',
        nameKey: 'testimonials.cards.metro.name',
        roleKey: 'testimonials.cards.metro.role',
      },
      {
        quoteKey: 'testimonials.cards.industry.quote',
        nameKey: 'testimonials.cards.industry.name',
        roleKey: 'testimonials.cards.industry.role',
      },
      {
        quoteKey: 'testimonials.cards.architect.quote',
        nameKey: 'testimonials.cards.architect.name',
        roleKey: 'testimonials.cards.architect.role',
      },
    ],
  },
  partners: {
    eyebrowKey: 'partners.eyebrow',
    titleKey: 'partners.title',
    descriptionKey: 'partners.description',
    items: [
      { nameKey: 'partners.items.metro.name', detailKey: 'partners.items.metro.detail' },
      { nameKey: 'partners.items.energy.name', detailKey: 'partners.items.energy.detail' },
      { nameKey: 'partners.items.developer.name', detailKey: 'partners.items.developer.detail' },
      { nameKey: 'partners.items.infrastructure.name', detailKey: 'partners.items.infrastructure.detail' },
    ],
  },
  faq: {
    eyebrowKey: 'faq.eyebrow',
    titleKey: 'faq.title',
    items: [
      { questionKey: 'faq.items.preparation.question', answerKey: 'faq.items.preparation.answer' },
      { questionKey: 'faq.items.warranty.question', answerKey: 'faq.items.warranty.answer' },
      { questionKey: 'faq.items.thermal.question', answerKey: 'faq.items.thermal.answer' },
      { questionKey: 'faq.items.support.question', answerKey: 'faq.items.support.answer' },
    ],
  },
  contact: {
    eyebrowKey: 'contact.eyebrow',
    titleKey: 'contact.title',
    descriptionKey: 'contact.description',
    addressKey: 'contact.address',
    phoneKey: 'contact.phone',
    emailKey: 'contact.email',
    form: {
      nameKey: 'contact.form.name',
      phoneKey: 'contact.form.phone',
      companyKey: 'contact.form.company',
      messageKey: 'contact.form.message',
      submitKey: 'contact.form.submit',
    },
  },
  subpageHero: {
    'why-us': {
      icon: 'shield-up',
      eyebrowKey: 'subpages.why.hero.eyebrow',
      badgeKey: 'subpages.why.hero.badge',
      titleKey: 'subpages.why.hero.title',
      descriptionKey: 'subpages.why.hero.description',
      stats: [
        { valueKey: 'subpages.why.hero.stats.0.value', labelKey: 'subpages.why.hero.stats.0.label' },
        { valueKey: 'subpages.why.hero.stats.1.value', labelKey: 'subpages.why.hero.stats.1.label' },
        { valueKey: 'subpages.why.hero.stats.2.value', labelKey: 'subpages.why.hero.stats.2.label' },
      ],
      cta: { labelKey: 'subpages.why.hero.cta', href: '/contact' },
      secondaryCta: { labelKey: 'subpages.why.hero.secondaryCta', href: '/projects' },
    },
    services: {
      icon: 'engineering',
      eyebrowKey: 'subpages.services.hero.eyebrow',
      badgeKey: 'subpages.services.hero.badge',
      titleKey: 'subpages.services.hero.title',
      descriptionKey: 'subpages.services.hero.description',
      stats: [
        { valueKey: 'subpages.services.hero.stats.0.value', labelKey: 'subpages.services.hero.stats.0.label' },
        { valueKey: 'subpages.services.hero.stats.1.value', labelKey: 'subpages.services.hero.stats.1.label' },
      ],
      cta: { labelKey: 'subpages.services.hero.cta', href: '/contact' },
      secondaryCta: { labelKey: 'subpages.services.hero.secondaryCta', href: '/solutions' },
    },
    solutions: {
      icon: 'layers',
      eyebrowKey: 'subpages.solutions.hero.eyebrow',
      badgeKey: 'subpages.solutions.hero.badge',
      titleKey: 'subpages.solutions.hero.title',
      descriptionKey: 'subpages.solutions.hero.description',
      stats: [
        { valueKey: 'subpages.solutions.hero.stats.0.value', labelKey: 'subpages.solutions.hero.stats.0.label' },
        { valueKey: 'subpages.solutions.hero.stats.1.value', labelKey: 'subpages.solutions.hero.stats.1.label' },
      ],
      cta: { labelKey: 'subpages.solutions.hero.cta', href: '/contact' },
      secondaryCta: { labelKey: 'subpages.solutions.hero.secondaryCta', href: '/projects' },
    },
    projects: {
      icon: 'projector',
      eyebrowKey: 'subpages.projects.hero.eyebrow',
      badgeKey: 'subpages.projects.hero.badge',
      titleKey: 'subpages.projects.hero.title',
      descriptionKey: 'subpages.projects.hero.description',
      stats: [
        { valueKey: 'subpages.projects.hero.stats.0.value', labelKey: 'subpages.projects.hero.stats.0.label' },
        { valueKey: 'subpages.projects.hero.stats.1.value', labelKey: 'subpages.projects.hero.stats.1.label' },
      ],
      cta: { labelKey: 'subpages.projects.hero.cta', href: '/contact' },
      secondaryCta: { labelKey: 'subpages.projects.hero.secondaryCta', href: '/why-us' },
    },
    articles: {
      icon: 'docs',
      eyebrowKey: 'subpages.articles.hero.eyebrow',
      badgeKey: 'subpages.articles.hero.badge',
      titleKey: 'subpages.articles.hero.title',
      descriptionKey: 'subpages.articles.hero.description',
      stats: [
        { valueKey: 'subpages.articles.hero.stats.0.value', labelKey: 'subpages.articles.hero.stats.0.label' },
        { valueKey: 'subpages.articles.hero.stats.1.value', labelKey: 'subpages.articles.hero.stats.1.label' },
      ],
      cta: { labelKey: 'subpages.articles.hero.cta', href: '/contact' },
      secondaryCta: { labelKey: 'subpages.articles.hero.secondaryCta', href: '/solutions' },
    },
    faq: {
      icon: 'support',
      eyebrowKey: 'subpages.faq.hero.eyebrow',
      badgeKey: 'subpages.faq.hero.badge',
      titleKey: 'subpages.faq.hero.title',
      descriptionKey: 'subpages.faq.hero.description',
      stats: [
        { valueKey: 'subpages.faq.hero.stats.0.value', labelKey: 'subpages.faq.hero.stats.0.label' },
      ],
      cta: { labelKey: 'subpages.faq.hero.cta', href: '/contact' },
      secondaryCta: { labelKey: 'subpages.faq.hero.secondaryCta', href: '/services' },
    },
    contact: {
      icon: 'phone',
      eyebrowKey: 'subpages.contact.hero.eyebrow',
      badgeKey: 'subpages.contact.hero.badge',
      titleKey: 'subpages.contact.hero.title',
      descriptionKey: 'subpages.contact.hero.description',
      stats: [
        { valueKey: 'subpages.contact.hero.stats.0.value', labelKey: 'subpages.contact.hero.stats.0.label' },
        { valueKey: 'subpages.contact.hero.stats.1.value', labelKey: 'subpages.contact.hero.stats.1.label' },
      ],
      cta: { labelKey: 'subpages.contact.hero.cta', href: '/contact' },
      secondaryCta: { labelKey: 'subpages.contact.hero.secondaryCta', href: '/faq' },
    },
    about: {
      icon: 'award',
      eyebrowKey: 'subpages.about.hero.eyebrow',
      badgeKey: 'subpages.about.hero.badge',
      titleKey: 'subpages.about.hero.title',
      descriptionKey: 'subpages.about.hero.description',
      stats: [
        { valueKey: 'subpages.about.hero.stats.0.value', labelKey: 'subpages.about.hero.stats.0.label' },
        { valueKey: 'subpages.about.hero.stats.1.value', labelKey: 'subpages.about.hero.stats.1.label' },
      ],
      cta: { labelKey: 'subpages.about.hero.cta', href: '/projects' },
      secondaryCta: { labelKey: 'subpages.about.hero.secondaryCta', href: '/contact' },
    },
  },
  pageSections: {
    home: [
      'hero',
      'catalog',
      'metrics',
      'highlights',
      'why',
      'services',
      'products',
      'caseStudies',
      'articles',
      'credentials',
      'testimonials',
      'process',
      'partners',
      'faq',
      'contact',
    ],
    'why-us': ['subpage-hero:why-us', 'highlights', 'why', 'metrics', 'process', 'testimonials', 'contact'],
    services: ['subpage-hero:services', 'services', 'process', 'caseStudies', 'partners', 'contact'],
    solutions: ['subpage-hero:solutions', 'products', 'highlights', 'faq', 'contact'],
    projects: ['subpage-hero:projects', 'caseStudies', 'credentials', 'partners', 'contact'],
    articles: ['subpage-hero:articles', 'articles-full', 'contact'],
    faq: ['subpage-hero:faq', 'faq', 'process', 'contact'],
    contact: ['subpage-hero:contact', 'contact'],
    about: ['subpage-hero:about', 'credentials', 'highlights', 'partners', 'testimonials', 'contact'],
  },
  articles,
  articleRecommendations: {
    ultraguard: ['ultraguard-moisture-barrier', 'guard-poly-green-building', 'coastal-infrastructure-waterproofing'],
    smartguard: ['smartguard-hydrostatic-defense', 'waterproofing-system-selection'],
    fastguard: ['fastguard-emergency-leak-stop', 'waterproofing-system-selection'],
    richguard: ['richguard-uv-protection', 'ultraguard-moisture-barrier'],
    default: ['waterproofing-system-selection', 'coastal-infrastructure-waterproofing'],
  },
  productsSection: {
    eyebrowKey: 'product.section.eyebrow',
    titleKey: 'product.section.title',
    descriptionKey: 'product.section.description',
  },
  products: [
    {
      id: 'ultraguard',
      slug: 'ultraguard',
      titleKey: 'product.ultraguard.title',
      taglineKey: 'product.ultraguard.tagline',
      descriptionKey: 'product.ultraguard.desc',
      illustrationKey: 'product.ultraguard.illustration',
      detailPath: '/products/ultraguard',
    },
    {
      id: 'bloguard',
      slug: 'bloguard',
      titleKey: 'product.bloguard.title',
      taglineKey: 'product.bloguard.tagline',
      descriptionKey: 'product.bloguard.desc',
      illustrationKey: 'product.bloguard.illustration',
      detailPath: '/products/bloguard',
    },
    {
      id: 'smartguard',
      slug: 'smartguard',
      titleKey: 'product.smartguard.title',
      taglineKey: 'product.smartguard.tagline',
      descriptionKey: 'product.smartguard.desc',
      illustrationKey: 'product.smartguard.illustration',
      detailPath: '/products/smartguard',
    },
    {
      id: 'fastguard',
      slug: 'fastguard',
      titleKey: 'product.fastguard.title',
      taglineKey: 'product.fastguard.tagline',
      descriptionKey: 'product.fastguard.desc',
      illustrationKey: 'product.fastguard.illustration',
      detailPath: '/products/fastguard',
    },
    {
      id: 'richguard',
      slug: 'richguard',
      titleKey: 'product.richguard.title',
      taglineKey: 'product.richguard.tagline',
      descriptionKey: 'product.richguard.desc',
      illustrationKey: 'product.richguard.illustration',
      detailPath: '/products/richguard',
    },
    {
      id: 'nanoguard',
      slug: 'nanoguard',
      titleKey: 'product.nanoguard.title',
      taglineKey: 'product.nanoguard.tagline',
      descriptionKey: 'product.nanoguard.desc',
      illustrationKey: 'product.nanoguard.illustration',
      detailPath: '/products/nanoguard',
    },
    {
      id: 'thermo-soundguard',
      slug: 'thermoguard-soundguard',
      titleKey: 'product.thermosound.title',
      taglineKey: 'product.thermosound.tagline',
      descriptionKey: 'product.thermosound.desc',
      illustrationKey: 'product.thermosound.illustration',
      detailPath: '/products/thermoguard-soundguard',
    },
    {
      id: 'floguard',
      slug: 'floguard',
      titleKey: 'product.floguard.title',
      taglineKey: 'product.floguard.tagline',
      descriptionKey: 'product.floguard.desc',
      illustrationKey: 'product.floguard.illustration',
      detailPath: '/products/floguard',
    },
    {
      id: 'armyguard',
      slug: 'armyguard',
      titleKey: 'product.armyguard.title',
      taglineKey: 'product.armyguard.tagline',
      descriptionKey: 'product.armyguard.desc',
      illustrationKey: 'product.armyguard.illustration',
      detailPath: '/products/armyguard',
    },
    {
      id: 'indax',
      slug: 'indax',
      titleKey: 'product.indax.title',
      taglineKey: 'product.indax.tagline',
      descriptionKey: 'product.indax.desc',
      illustrationKey: 'product.indax.illustration',
      detailPath: '/products/indax',
    },
    {
      id: 'flexcoat',
      slug: 'flexcoat',
      titleKey: 'product.flexcoat.title',
      taglineKey: 'product.flexcoat.tagline',
      descriptionKey: 'product.flexcoat.desc',
      illustrationKey: 'product.flexcoat.illustration',
      detailPath: '/products/flexcoat',
    },
    {
      id: 'grotex',
      slug: 'grotex',
      titleKey: 'product.grotex.title',
      taglineKey: 'product.grotex.tagline',
      descriptionKey: 'product.grotex.desc',
      illustrationKey: 'product.grotex.illustration',
      detailPath: '/products/grotex',
    },
    {
      id: 'metalguard',
      slug: 'metalguard',
      titleKey: 'product.metalguard.title',
      taglineKey: 'product.metalguard.tagline',
      descriptionKey: 'product.metalguard.desc',
      illustrationKey: 'product.metalguard.illustration',
      detailPath: '/products/metalguard',
    },
    {
      id: 'fireguard',
      slug: 'fireguard',
      titleKey: 'product.fireguard.title',
      taglineKey: 'product.fireguard.tagline',
      descriptionKey: 'product.fireguard.desc',
      illustrationKey: 'product.fireguard.illustration',
      detailPath: '/products/fireguard',
    },
    {
      id: 'luminex',
      slug: 'luminex',
      titleKey: 'product.luminex.title',
      taglineKey: 'product.luminex.tagline',
      descriptionKey: 'product.luminex.desc',
      illustrationKey: 'product.luminex.illustration',
      detailPath: '/products/luminex',
    },
  ],
  productDetails: {
    ultraguard: {
      illustrationKey: 'product.ultraguard.illustration',
      metrics: [
        { icon: 'drop', value: '1.2 kg/m²', labelKey: 'detail.ultraguard.metrics.coverage' },
        { icon: 'clock', value: '6h', labelKey: 'detail.ultraguard.metrics.cure' },
        { icon: 'shield-up', value: 'Class A', labelKey: 'detail.ultraguard.metrics.barrier' },
      ],
      overviewKey: 'detail.ultraguard.overview',
      performanceKey: 'detail.ultraguard.performance',
      applicationsKey: 'detail.ultraguard.applications',
      featuresKey: 'detail.ultraguard.features',
    },
    bloguard: {
      illustrationKey: 'product.bloguard.illustration',
      metrics: [
        { icon: 'crystal', value: '4mm', labelKey: 'detail.bloguard.metrics.depth' },
        { icon: 'clock', value: '90min', labelKey: 'detail.bloguard.metrics.reaction' },
        { icon: 'lab-beaker', value: 'pH 11', labelKey: 'detail.bloguard.metrics.ph' },
      ],
      overviewKey: 'detail.bloguard.overview',
      performanceKey: 'detail.bloguard.performance',
      applicationsKey: 'detail.bloguard.applications',
      featuresKey: 'detail.bloguard.features',
    },
    smartguard: {
      illustrationKey: 'product.smartguard.illustration',
      metrics: [
        { icon: 'layers', value: 'Mix 4:1', labelKey: 'detail.smartguard.metrics.system' },
        { icon: 'shield-check', value: '12 bar', labelKey: 'detail.smartguard.metrics.pressure' },
        { icon: 'clock', value: '40 min', labelKey: 'detail.smartguard.metrics.ready' },
      ],
      overviewKey: 'detail.smartguard.overview',
      performanceKey: 'detail.smartguard.performance',
      applicationsKey: 'detail.smartguard.applications',
      featuresKey: 'detail.smartguard.features',
    },
    fastguard: {
      illustrationKey: 'product.fastguard.illustration',
      metrics: [
        { icon: 'stopwatch', value: '60s', labelKey: 'detail.fastguard.metrics.stop' },
        { icon: 'temperature', value: '≥5°C', labelKey: 'detail.fastguard.metrics.temp' },
        { icon: 'hammer', value: '16 MPa', labelKey: 'detail.fastguard.metrics.strength' },
      ],
      overviewKey: 'detail.fastguard.overview',
      performanceKey: 'detail.fastguard.performance',
      applicationsKey: 'detail.fastguard.applications',
      featuresKey: 'detail.fastguard.features',
    },
    richguard: {
      illustrationKey: 'product.richguard.illustration',
      metrics: [
        { icon: 'brush', value: '400%', labelKey: 'detail.richguard.metrics.elasticity' },
        { icon: 'uv', value: 'UV 500h', labelKey: 'detail.richguard.metrics.uv' },
        { icon: 'palette', value: '12 colors', labelKey: 'detail.richguard.metrics.colors' },
      ],
      overviewKey: 'detail.richguard.overview',
      performanceKey: 'detail.richguard.performance',
      applicationsKey: 'detail.richguard.applications',
      featuresKey: 'detail.richguard.features',
    },
    nanoguard: {
      illustrationKey: 'product.nanoguard.illustration',
      metrics: [
        { icon: 'nano', value: '92°', labelKey: 'detail.nanoguard.metrics.angle' },
        { icon: 'clock', value: '15min', labelKey: 'detail.nanoguard.metrics.dry' },
        { icon: 'leaf', value: 'VOC Free', labelKey: 'detail.nanoguard.metrics.voc' },
      ],
      overviewKey: 'detail.nanoguard.overview',
      performanceKey: 'detail.nanoguard.performance',
      applicationsKey: 'detail.nanoguard.applications',
      featuresKey: 'detail.nanoguard.features',
    },
    'thermoguard-soundguard': {
      illustrationKey: 'product.thermosound.illustration',
      metrics: [
        { icon: 'thermo', value: '0.021 λ', labelKey: 'detail.thermosound.metrics.lambda' },
        { icon: 'sound', value: '18dB', labelKey: 'detail.thermosound.metrics.acoustic' },
        { icon: 'spray', value: 'Foam', labelKey: 'detail.thermosound.metrics.tech' },
      ],
      overviewKey: 'detail.thermosound.overview',
      performanceKey: 'detail.thermosound.performance',
      applicationsKey: 'detail.thermosound.applications',
      featuresKey: 'detail.thermosound.features',
    },
    floguard: {
      illustrationKey: 'product.floguard.illustration',
      metrics: [
        { icon: 'resistance', value: 'CS 90 MPa', labelKey: 'detail.floguard.metrics.strength' },
        { icon: 'chemical', value: 'pH 3-12', labelKey: 'detail.floguard.metrics.chemical' },
        { icon: 'globe-grid', value: 'ISO 5470', labelKey: 'detail.floguard.metrics.abrasion' },
      ],
      overviewKey: 'detail.floguard.overview',
      performanceKey: 'detail.floguard.performance',
      applicationsKey: 'detail.floguard.applications',
      featuresKey: 'detail.floguard.features',
    },
    armyguard: {
      illustrationKey: 'product.armyguard.illustration',
      metrics: [
        { icon: 'shield-check', value: 'Hybrid', labelKey: 'detail.armyguard.metrics.hybrid' },
        { icon: 'spray', value: '2k', labelKey: 'detail.armyguard.metrics.mix' },
        { icon: 'helmet', value: 'IMPA', labelKey: 'detail.armyguard.metrics.resistance' },
      ],
      overviewKey: 'detail.armyguard.overview',
      performanceKey: 'detail.armyguard.performance',
      applicationsKey: 'detail.armyguard.applications',
      featuresKey: 'detail.armyguard.features',
    },
    indax: {
      illustrationKey: 'product.indax.illustration',
      metrics: [
        { icon: 'adhesion', value: '3.5 MPa', labelKey: 'detail.indax.metrics.adhesion' },
        { icon: 'clock', value: '2h', labelKey: 'detail.indax.metrics.recoat' },
        { icon: 'chemical', value: 'Solvent-Free', labelKey: 'detail.indax.metrics.solvent' },
      ],
      overviewKey: 'detail.indax.overview',
      performanceKey: 'detail.indax.performance',
      applicationsKey: 'detail.indax.applications',
      featuresKey: 'detail.indax.features',
    },
    flexcoat: {
      illustrationKey: 'product.flexcoat.illustration',
      metrics: [
        { icon: 'layers', value: '3-Part', labelKey: 'detail.flexcoat.metrics.system' },
        { icon: 'stretch', value: '280%', labelKey: 'detail.flexcoat.metrics.elasticity' },
        { icon: 'temperature', value: '120°C', labelKey: 'detail.flexcoat.metrics.temp' },
      ],
      overviewKey: 'detail.flexcoat.overview',
      performanceKey: 'detail.flexcoat.performance',
      applicationsKey: 'detail.flexcoat.applications',
      featuresKey: 'detail.flexcoat.features',
    },
    grotex: {
      illustrationKey: 'product.grotex.illustration',
      metrics: [
        { icon: 'adhesion', value: '4.1 MPa', labelKey: 'detail.grotex.metrics.adhesion' },
        { icon: 'clock', value: '8h', labelKey: 'detail.grotex.metrics.cure' },
        { icon: 'brush', value: 'High Build', labelKey: 'detail.grotex.metrics.build' },
      ],
      overviewKey: 'detail.grotex.overview',
      performanceKey: 'detail.grotex.performance',
      applicationsKey: 'detail.grotex.applications',
      featuresKey: 'detail.grotex.features',
    },
    metalguard: {
      illustrationKey: 'product.metalguard.illustration',
      metrics: [
        { icon: 'rust', value: 'Convert', labelKey: 'detail.metalguard.metrics.convert' },
        { icon: 'clock', value: '20min', labelKey: 'detail.metalguard.metrics.react' },
        { icon: 'shield-up', value: 'Dual Layer', labelKey: 'detail.metalguard.metrics.layers' },
      ],
      overviewKey: 'detail.metalguard.overview',
      performanceKey: 'detail.metalguard.performance',
      applicationsKey: 'detail.metalguard.applications',
      featuresKey: 'detail.metalguard.features',
    },
    fireguard: {
      illustrationKey: 'product.fireguard.illustration',
      metrics: [
        { icon: 'flame', value: '2h', labelKey: 'detail.fireguard.metrics.rating' },
        { icon: 'leaf', value: 'Water-Based', labelKey: 'detail.fireguard.metrics.base' },
        { icon: 'certificate', value: 'EN 13381', labelKey: 'detail.fireguard.metrics.standard' },
      ],
      overviewKey: 'detail.fireguard.overview',
      performanceKey: 'detail.fireguard.performance',
      applicationsKey: 'detail.fireguard.applications',
      featuresKey: 'detail.fireguard.features',
    },
    luminex: {
      illustrationKey: 'product.luminex.illustration',
      metrics: [
        { icon: 'light', value: '12h+', labelKey: 'detail.luminex.metrics.glow' },
        { icon: 'traffic', value: 'T2', labelKey: 'detail.luminex.metrics.class' },
        { icon: 'rain', value: 'IP67', labelKey: 'detail.luminex.metrics.weather' },
      ],
      overviewKey: 'detail.luminex.overview',
      performanceKey: 'detail.luminex.performance',
      applicationsKey: 'detail.luminex.applications',
      featuresKey: 'detail.luminex.features',
    },
  },
};
